language: ruby
env: RACK_ENV=development
sudo: false
rvm:
- 2.0.0
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_1590a5cf432e_key -iv $encrypted_1590a5cf432e_iv
  -in escualo_rsa.enc -out escualo_rsa -d
- docker pull mumuki/mumuki-rspec-worker
after_success:
- wget https://raw.githubusercontent.com/mumuki/mumuki-escualo/master/travis_deploy && chmod u+x travis_deploy && ./travis_deploy rspec runners.mumuki.io
