sudo: required
language: ruby
env: RACK_ENV=development
rvm:
- 2.0.0
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_1590a5cf432e_key -iv $encrypted_1590a5cf432e_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- docker pull mumuki/mumuki-rspec-worker
after_success:
- ./escualo rspec 162.243.111.176
